# Generated by Django 5.2.14 on 2026-05-28 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('example', '0002_dialogactionuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='菜单名称')),
                ('icon', models.CharField(max_length=50, verbose_name='图标名称')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='路由路径')),
                ('permission', models.CharField(blank=True, max_length=100, null=True, verbose_name='权限标识')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('group_label', models.CharField(blank=True, max_length=50, null=True, verbose_name='分组标签')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='example.menuitem', verbose_name='父菜单')),
            ],
            options={
                'verbose_name': '菜单项',
                'verbose_name_plural': '菜单项',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RoleMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='角色')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.menuitem', verbose_name='菜单项')),
            ],
            options={
                'verbose_name': '角色菜单权限',
                'verbose_name_plural': '角色菜单权限',
                'unique_together': {('group', 'menu_item')},
            },
        ),
    ]
